image: python:3.6

stages:
  - build
  - run
  - test


build:
  type: build
  script:
    - python -V                                   # Print out python version for debugging
    - apt-get update -q -y
    - apt-get install -y curl
    - pip3 install -r requirements.txt

run:
  type: run
  script:
  - python3 -m node_monitor_agent
 
test:
  type: test
  script:
    - curl -X GET --header 'Accept: application/json' --header 'api_key: 111' 'http://127.0.0.1:9001/boot_time'
