image: python:3.6

stages:
  - test

build:
  stage: test
  before_script:
    - python -V                                   # Print out python version for debugging
    - apt-get update -q -y
    - apt-get install curl -y
    - pip3 install -r requirements.txt 
  script:
    - python3 -m node_monitor_agent &
    - ./test.sh
