before_script:                                  # Print out python version for debugging
    - apt-get update -q -y
    - apt-get install -y curl # python3 python3-pip 
    - python3 -V 
    - pip3 install -r requirements.txt

stages:
  - python3
#  - ubuntu14
#  - ubuntu16

python3:
  stage: python3
  image: python:3 
  script:
    - python3 -m node_monitor_agent &
    - sleep 5
    - ./test.sh

#ubuntu14:
#  stage: ubuntu14
#  image: ubuntu:14.04  
#  script:
#    - python3 -m node_monitor_agent &
#    - sleep 5
#    - ./test.sh

#ubuntu16:
#  stage: ubuntu16
#  image: ubuntu:16.04  
#  script:
#    - python3 -m node_monitor_agent &
#    - sleep 5
#    - ./test.sh

