---
swagger: "2.0"
info:
  description: "API for server management"
  version: "1.0.0"
  title: "DevOpsHelper"
  contact:
    email: "kadajgen@gmail.com"
host: "127.0.0.1:9000"
basePath: "/api"
tags:
- name: "agent"
  description: "Check agent status"
- name: "services"
  description: "Check agent status"
- name: "version"
  description: "Check agent status"
- name: "hardware"
  description: "Check agent status"
schemes:
- "http"
paths:
  /agent:
    get:
      tags:
      - "agent"
      summary: "Check ping"
      description: "Return to the client available groups and transform them to buttons"
      operationId: "agent_get"
      parameters: []
      responses:
        200:
          description: "Возвращает ответ в формате JSON."
        500:
          description: "Возвращает: The server encountered an internal error and was\
            \ unable to complete your request"
      x-swagger-router-controller: "zencow_agent.controllers.agent_controller"
  /agent/{hwid}:
    get:
      tags:
      - "agent"
      summary: "Check access"
      description: "Return to the client available groups and transform them to buttons"
      operationId: "agent_hwid_get"
      parameters:
      - name: "hwid"
        in: "path"
        description: "Unique hardware id"
        required: true
        type: "string"
        maxLength: 32
        minLength: 32
      responses:
        200:
          description: "Возвращает ответ в формате JSON."
        500:
          description: "Возвращает: The server encountered an internal error and was\
            \ unable to complete your request"
      x-swagger-router-controller: "zencow_agent.controllers.agent_controller"
  /agent/{hwid}/services/{service}:
    get:
      tags:
      - "services"
      summary: "return all available groups"
      description: "Return to the client available groups and transform them to buttons"
      operationId: "agent_hwid_services_service_get"
      parameters:
      - name: "hwid"
        in: "path"
        description: "ID of the required group"
        required: true
        type: "string"
        maxLength: 60
        minLength: 16
      - name: "service"
        in: "path"
        description: "ID of the required group"
        required: true
        type: "string"
      responses:
        200:
          description: "Возвращает ответ в формате JSON."
        500:
          description: "Возвращает: The server encountered an internal error and was\
            \ unable to complete your request"
      x-swagger-router-controller: "zencow_agent.controllers.services_controller"
  /agent/{hwid}/version/{service}/{user}:
    get:
      tags:
      - "version"
      summary: "return all available groups"
      description: "Return to the client available groups and transform them to buttons"
      operationId: "agent_hwid_version_service_user_get"
      parameters:
      - name: "hwid"
        in: "path"
        description: "ID of the required group"
        required: true
        type: "string"
        maxLength: 60
        minLength: 16
      - name: "service"
        in: "path"
        description: "ID of the required group"
        required: true
        type: "string"
      - name: "user"
        in: "path"
        description: "ID of the required group"
        required: true
        type: "string"
      responses:
        200:
          description: "Возвращает ответ в формате JSON."
        500:
          description: "Возвращает: The server encountered an internal error and was\
            \ unable to complete your request"
      x-swagger-router-controller: "zencow_agent.controllers.version_controller"
  /agent/{hwid}/iron/{device}:
    get:
      tags:
      - "hardware"
      summary: "return all available groups"
      description: "Return to the client available groups and transform them to buttons"
      operationId: "agent_hwid_iron_device_get"
      parameters:
      - name: "hwid"
        in: "path"
        description: "ID of the required group"
        required: true
        type: "string"
        maxLength: 60
        minLength: 16
      - name: "device"
        in: "path"
        description: "ID of the required group"
        required: true
        type: "string"
        enum:
        - "ram"
        - "disk"
        - "la"
        - "fqdn"
        - "distr"
        - "cpu"
      responses:
        200:
          description: "Возвращает ответ в формате JSON."
        500:
          description: "Возвращает: The server encountered an internal error and was\
            \ unable to complete your request"
      x-tags:
      - tag: "examples"
      x-swagger-router-controller: "zencow_agent.controllers.hardware_controller"
definitions: {}
